version: "2"
run:
  timeout: 5m
  go: 1.26.2
  build-tags:
    - goexperiment.arenas
    - goexperiment.goroutineleakprofile
    - goexperiment.jsonv2
    - goexperiment.runtimesecret
    - goexperiment.simd
  allow-parallel-runners: true
  allow-serial-runners: true
output:
  formats: {}
linters:
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - gosmopolitan
    - govet
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usetesting
    - wastedassign
    - wrapcheck
    - zerologlint
  settings:
    dupl:
      threshold: 100
    exhaustruct:
      exclude:
        - os/exec.Cmd
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - exhaustruct
          - gochecknoglobals
          - goconst
          - dupl
          - paralleltest
          - errcheck
          - revive
      - path: client\.go
        linters:
          - bodyclose
          - exhaustruct
      - path: options\.go
        linters:
          - exhaustruct
          - revive
      - text: now is unused
        linters:
          - unparam
      - path: types\.go
        linters:
          - revive
      - path: errors\.go
        linters:
          - revive
      - path: helpers\.go
        linters:
          - wrapcheck
formatters:
  enable:
    - gci
    - goimports
    - gofumpt
    - golines
  exclusions:
    generated: lax
issues: {}
